language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: YXV0xhhL234T6Op0TGcdkHOUjqWJdFNxSYl7/fSB55+kL2WL7WnbXd+hLo6gV3FsNv0F5+eEKp06Y3u5ytDNzwi8dwGuTRQItQIOwYzKmMvcyJsfww0SXX9l46cEqFcGX1K1pHS0+Oz126YIH7qdq1yWwDNdwrTO6l6gZtcf15ezP2ItvlDP1yDyRv3Kz0WlhzeiwlFREyo6I4Ya8uKAMPir3iWYxQeZUkyYq3nn40UuJ2rsqgEEw9VnujuSNBPurh9k6a/q945xxpjXQdWFwH0/XfaWGc+YnDKyQuO3ZfAOh/CNFIqYJMH7qHfmCqSi/yYp0wEEUEyqWVeHuLC3yCyTjxS96RUEm8WcbvTlJYNyF5NPe9vuHAXR5xfxD0EofxpA3wf018Nx8D602BaFCzDJGpDkRhpfagEN4LgjTJNwK+oa9xGd9ehQap+iZGcvkQzE91KnxtWkMewza31ItRFK23axol8xnBPtx7kQMuISQtagJhwzxvOhRHnQuhFzIrfuD7qcn9fQgipFtoIF0uEmy+KUNazyR3p6PJpfUFgBVUG1hSNj7wx+xQn4JeeEVNYJkCluaYHGJvRlUPiUPe4ubSAdg73HWq8yGMkp7lGt8jCvKeC8/jK4pWPIY5N5L+MIg3Iy0CHzFFQr8Ww5EgUQeoJJJHknnzP+Tb1RSDg=
  skip_cleanup: true
