language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: NkwVGpx0k1hq2RbJDGCu2bRglOG/Dr79WYJUDAkOnoZKiZcTkbZK4VmHrOiK6YwJC0N0f0Vsc1s6ZjpFCRqt1sGLXfdGs/9+3CE7snXAmEb3NEZwH+1AifHaxmtsFVgxZU3Z2erE+1Z1XkENDQEWdU106fqBYdo2ejYiaxu3Bb2x17ptTGJad2ou4a+KsuPtyQrSMlQ+Psk+vFTILRo3RU6/Q1ihNxaWQ8v9jyVYAnZj6Xp9fIJcsjV6AoAY4zBABAz8LljK9gsPW4idKavfRuZu2iMbAmLv/G8NdCD1qEUXzlh2NGMRCPa59lHovh9aEdourQ0mB+lV8NsAxLrNDaoXEl2kP76ttjz0NsVuP9dUQ6768GdeJQlr5aFrTuW/A4gSzji6nyBjG/4Y+erxdimHEJ/Zb6kEbAGG1P/OSZ6m1S1Sz/nf9RyT8SnRmALBs9ZHq8t4V4LLB1Cmtycja57kzcTvHglGxQAeLT8/kNUehDBnjMWZ5LKjwAn5a7k3Z8xShqKZEMjhI3IibkTssK3vRRWHDZE5VGtnr4ze0AhmPL+GtSsYBlltS/EWCnIzwCAnjgXg6554y/sfyvpHXXS+iXT6ASi/3BQq3+FgMNYNBw1M3njOi39laCASPHzYR/VaXAfzoB5eAPNm0PZpw4Lc+GvtX6lUizKgHoEhCYk=
  skip_cleanup: true
  on:
    tags: true
    python: 3.6
