language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: AhpVVXM+ssopQTIGrN1fOUauOvFbUuGlMuA2Fcr/Jk8avDGYWaC6rpHbSBkbR5PDbc6/MkTLUhpkXR0E16LWAlFwPDzqGPXG4jgGsX0DHiKIpRmG05aknQRtJhwfdpziGC8EnW6NJyw4HEcP8LxUlRCAoUkGkbum7zJR8vW6HwXE71EL+iaQRAzO6sIMAXcEu0DPjuHhOVIQPWybeeKDQNQVfn9ifuhNkYdOi+vnyZEKlgCas84+DDF0AhwkYE66De5HiLhzGyW8xHm06yi8+v/7u9eKAPac0IfSies1jKvBHHy+0ZBgOdQMb0dN5PeQJh0BqLE54yMRltXLY8WjbZzVTALDxA5IZDD6eyCK6ae3QgVqsvI9gBkHB3N5EK6dIxf5+boVlSq7WFVcrPsDRVxKJgf9BhWziF0u1YkeOiw/0Sp/J/lrv8+RL6KalhqMNDrG2q9ORrNjjwj+FpCPLDR756/IB7jaVdfcYBsKhwgGoZHJdVcl8jlR0VZM2j7SXEuJBGgrX/MdudaTY+kxhP8Bto6A+gAmh2qMOdnU4h3msu7/Jw23rD0vxOwAAlL5wzjZQAahSbIw3FkPTrLk2TYlxI2Qk8MUpVedyaEUniIueRmM36oz1ZPJh1W2VVrf6EGK2fugYfg6D462LLJ6lLv6nEexnwZNLDDApwa4bBA=
  skip_cleanup: true
  on:
    tags: true
