language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: aLHeF3C2gppACB+VIzvYsTq0nBPfMOTgnjVSy9cmV9cMnQXR4h70hQ3jx8tJ3A6M5MfJdheq6monPI9DK8m9wZgYf5MSEkEAF4MovhjWDJJtn6lHzbYxlHhXTZUqui6DBrHcU7hR1butXNDWFPEhtc4EU8GV3kPM6TdmQX5RF+lKurW6q05w0QcV+8ZomzbwKw4e3nr3OfcV2xjYwbnCRqY5c7JhIzVPRtrXIbMJhCLk7TtQbzFmuhgPqDednn6914b38zjxvvWrxMXO1lJhQyVyQWgJ4XFygLmlVi2SoRmzCtHMZ6QHId1ipn9P6hNNzwjNMe7Xgy7n3njXAGRQalYKdooOH6rBLuGslfsH4Gdt2if9KfT7yPvDFdD8LmUTUNAb6erQQuQL/IktoP4VQaci3MYrMTW9V+yCE4UE/7ahqmzbY+1SUHfYu7S9OcBtH74Lh2f2ilqSWTx8dmVOg303Z0re4l2jKtzC9guWNhjJXtydcirxkYytd2rz9YKKHXmaGURNxW/UsyFLyb0ptfgrNx5JrTYzgy/qfWLT9GNzec5GmIM0D+o2T10dcsgT/ryLpwxjp3rZjng+zLUyVOg2yJpVwKrsy1ZxFyFMGePyy4n15bMqWkRY1j1kfM0YFwCfOhTCS1Lb/b87/ttxTD3G/s5k0sDvQQcaxPdEppo=
  skip_cleanup: true
  on:
    tags: true
    python: 3.6
