language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: hJlhz71Gaps3XabjeK3U0pZMo2eFT0sBV///NWfk0ZrTNFsuUu3QIbLKan9ySIhDiut4J3qZN7syKr2B5ZQqR7B9aWDSzbHoSNnjucIdgrFqCfRvYUsdwUprP25y3FEk7YINnDfxKeQxtUEgfR+9t/Vw9qN9CnabjxTxdVdWN5smGxVyAT12i2argE6psmbsJRWTNNPaK6DNMey7fNuyZSONtmIYfyqBHYQxZy9n5UpYN0+BtzeZvNM2lnd0nl+71PxRsnXRAke/ZPlSZ5OVwr2N1W92JRCGHLXExP7p20Y+Jtd9WnKkOrCITM8q5t/p63fqWw2Jzzp+oyfM/p16TKUjD2+CDFEjDmMRi0DFzx1X/e0grRkbirOyxkgupGh9FBgUqdLcvCBNoacIR4CTQrpBUxGZNWfwVh0EM6Tyd8Bx18nnPnV3tvHrdLfSI95bqMAHUCjkbyrhV/Zay5QTk5jdVIUvEMJ2IwQP8ueyOgDGsoAPds12W1408oLIvajD5IKfeN7KvvtjDkap97pq0JaBqNqgLScUdglzllcuzEHXjr2oGYeV9HnhdQVRX9ldoONrMplUyluUw8Q2v+6Nps9FHIoaUiIYSWXjSDTleYtspenvj/URfIur5Phpn3Ug/pIguoo3NrSL+bkGjY+beKqYd5NtZ3lWkBKw1W7wChE=
  skip_cleanup: true
  on:
    branch: master
    python: 3.6
