language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: WfnmbOZqdYA5cfuNjHGlZjjcKFhfAPRE4ymay0UOk3aqSd3tkVzXyz/ZhBU8zUsWpKxx+M9q6yh7l7ECENBmz8d4nd3gzzjCePhHSqA1wI3LyivyChun/ap+e0JoJNCmx+vYJMtuyJu6zCVVv+q0E3u2D3o9AbHA6VRU918s2Wh7a2B659bYbWmocAYA/GKELlznLmnay5ESbgAIfF2B8TH05bJE3XtWJOstHnIIIKwndYDk6+vRoHV0vQN04FwdLJAt9z7UmX8n5GbhEd8NBU8Hr7DKKvx7jh33NfsinjL/16pxv5WsuwDoi4m54iuxdf+qvSmptqglPZBUKhYvO8Bft5Htm0gNs/AgqGzY9mypPDrmIljWpK6a7WhlySHhOVKnen1deGUcdu25FI6elQBIi/UoQJPQ4xRW2PlBfnMHcHCAjQbzfvKF+3rkVQVSZrUqQTAeobUNB52TaMBL6S+r8/HKGE9tMZlcpgGXSlu34Qfra1+kwBTqVDSAEPRaZrgav+C/36uAwwMLJjZsm5LKkqiRnCFqunfTCp/CkATUoyG4thPwsqNWcTx3HeGDd+sIht5o/ASzZOUKo4zdL6LwoLWAA0+dobblk19iykJOTbdntWFTx/7/KeZ7z09mfKcdMlPTMEyOX2GVGXhQFtOwS/077kiIEpvxb8jlkjA=
  on:
    tags: true
    python: 3.6
