language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: VTYGIETy1+uEDFYx33s1vt/7mrY3XyUef4sQ8xmsHQli2oQUnxRH83a0H66cxR2H1YBzAuReuo6niSXf/1Sf0IsNRZ6eB9lp61L+GzbFqyGee5NUYsLC0tsiOGRh/MDYXKzq2CsBI0VvaaeAPKgltRnWcws2qf9nLrY+6EUxpcB8XnoOzWlHjzzHAojAMP+u1AOlFnl2Ot5LG5oyzo9seOiNIydNVt1O0Ds/TOyY1R53p9Y9NTuQBsXAvljZj+xU8GyxIdJTkC5Zb70+yDC0aA2ovbxrYSU80ytMPoIALSxLjuttW1Kqsb9ybQhbDso/tQ4MO40VdtnQOSc+2KW80IWrDTvLIhRuQSF+gF0TpfzrsK5cPb+KrMdWSIy+V5Aisv+Frjrw57bCYAqHEXzb4a49mL/Lt7EJ0Xteb2d+otzR/kK4sHbKiCHvWNfQmVvAMgGmnuM7+lvhTM87tnVJLOaaD0S4bQTvXXIQTvvbcyJXfr92+GrYvQHtdjQ33SDFUbwvefoC+ah4EsOyzkaKrSWLjL8aGKjmSrNu07lpFn8Tl5ta32NC1VbVFK/lYfJMnr3gY5W1GGJiaRjhwcGaO9A+EWrW9Dn/5Ve++ViBd5+yy7PjtXkat9xbcTXPaMgi9T+juVF7szn4JfVQA/QI7rl+yWxD8vAH64gc6hBK3/s=
  skip_cleanup: true
  on:
    tags: true
    python: 3.6
env:
  global:
    secure: JiokJ/+1dJf1WcHOZIKOKY7VkJ+FAsXnsifWJxgIBd8oWTMTL4iyheQNJTsfisvJCfOKQvJJrHJWJs+rN4ZDrv5mDt73GpBLpOMsJW4iTVGTIzDZvxo3CjAoEcdpRgluFKclVUixWpZTPZ/c3RcGyl6DDrw+G+Z1fkv0n/sQDqGq7UKXIL/eGTox6vIvHKuE99u3ugjuTaqPCX1rNcZkATJqc3AaWByUIr7pd8zTXGM2i4aP8aCdowqE31U+aeX9L/dQIqvDpUWd6vrsxZj96awtWYE5x60EvNbuZJPqJMeLv6EGA/2FNpNbc/RKCY37wv7Gwq879RfcFlPSeq4aI78RX4OAB0or0nQF4a3KBxKIbg6MzNhBq8MYtj7PvHncUOeuOH1onci1+RGn9iw06RBwRahau6cr6mY+nbuSaETUSP8OeZuCPKxsE9b0+7Zarj8vVQV1IEy7GXChLne8fh2D1HTPVg2O9aKQqVyJ+K3ciCCvfXDuNelbVxX3C7j7jgrS4GUTNryXpUs+XNCNLTI3tdwLlgGfzMqlCWKayHV+Noxn33KC/AF+PLVi3ZkDR+lqzMpc8KCtcj/RAoVTHj8wcF/E2D39VbGkDPY7J0FkNBvF7FWLr6/+7UsbGxBhx3GO+qp6lelfA8oewXqeFyTeHb5qP77rhouI/uQUyD4=
